# Site settings
title: Aidi Tan
email: aidistan@163.com
description: Better to light one candle than to curse the darkness.
url: "http://aidistan.site"
baseurl: ""

# Build settings
markdown: kramdown
