# Site settings
title: Aidi Tan
email: aidistan@163.com
description: Better to light one candle than to curse the darkness.
url: "https://aidistan.site"
baseurl: ""

# Build settings
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md"]
